### ISSUE TITLE
[FEATURE] Change the Navbar color . 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#227]
### Description

Change the header color and fix the border size.

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161395689-d756090c-62ec-4cf5-8c34-c452f61c5635.png)

**Comment by The-Arshad-Khan** [comment]
Kindly Assign this issue to me @The-Shivam-garg under GSSOC'22

**Comment by The-Shivam-garg** [comment]
sure ! @The-Arshad-Khan you can start working on this issue

**Comment by The-Arshad-Khan** [comment]
Thank you @The-Shivam-garg ❤️

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I am a GSSOC'22 contributor . I have solved this issue . I have changed the size of navbar so that it does not overlap with the man's icon . I have also changed the style of items in navbar and included the sign in option in the navbar rather than having a button as it was coming and hiding the items in other pages . I have attached the screenshot below . 

I think the header color is perfect as it aligns with the theme . Can you please assign this issue to me . I have send the PR . You can review and merge it .

![image](https://user-images.githubusercontent.com/73689669/161570709-94e4f0b5-7b7f-4162-afa2-e260fd17eec7.png)

**Comment by Rishita489** [comment]
Hey , @The-Shivam-garg , I have fixed the issue and send the PR . You can review and merge it .
